// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Psts.Web.Data;

#nullable disable

namespace psts.web.Migrations
{
    [DbContext(typeof(PstsDbContext))]
    [Migration("20260221185309_SpinOffApprovalsToNewApprovalLedger")]
    partial class SpinOffApprovalsToNewApprovalLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Psts.Web.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSuccessfulLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LoginPassAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("OIDCAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResetPassOnLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("StaleAccountLockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Psts.Web.Data.PstsClientProfile", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPOCeMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPOCfName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPOClName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPOCtPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeePOCId")
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("ClientId");

                    b.HasIndex("EmployeePOCId")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("PstsClientProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_Project_ShortCode_Format", "char_length(\"ShortCode\") = 4 AND \"ShortCode\" = upper(\"ShortCode\")");
                        });
                });

            modelBuilder.Entity("Psts.Web.Data.PstsProjectDefinition", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeePOCId")
                        .HasColumnType("text");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("EmployeePOCId")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("PstsProjectDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_Project_ShortCode_Format", "char_length(\"ShortCode\") = 4 AND \"ShortCode\" = upper(\"ShortCode\")");
                        });
                });

            modelBuilder.Entity("Psts.Web.Data.PstsTaskDefinition", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("PstsTaskDefinitions", t =>
                        {
                            t.HasCheckConstraint("CK_Project_ShortCode_Format", "char_length(\"ShortCode\") = 4 AND \"ShortCode\" = upper(\"ShortCode\")");
                        });
                });

            modelBuilder.Entity("psts.web.Data.AppSettings", b =>
                {
                    b.Property<string>("Setting")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Setting");

                    b.ToTable("AppSettingss");
                });

            modelBuilder.Entity("psts.web.Data.PstsBillingRateResolutionSchedule", b =>
                {
                    b.Property<long>("BillingRateNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BillingRateNum"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("BillingRateNum");

                    b.HasIndex("ChangedBy")
                        .IsUnique();

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.ToTable("pstsBillingRateResolutionSchedules");
                });

            modelBuilder.Entity("psts.web.Data.PstsTimeAdjustmentApprovalLedger", b =>
                {
                    b.Property<Guid>("ApprovedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalAuthority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ApprovalTimeStamp")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("ApprovingUserId")
                        .HasColumnType("text");

                    b.Property<bool>("Disapproved")
                        .HasColumnType("boolean");

                    b.Property<long>("TransactionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionNum"));

                    b.HasKey("ApprovedTransactionId");

                    b.HasIndex("ApprovingUserId");

                    b.ToTable("PstsTimeAdjustmentApprovalLedger");
                });

            modelBuilder.Entity("psts.web.Data.PstsTimeTransactions", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EnteredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EnteredTimeStamp")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsAdjustment")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<long>("TransactionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionNum"));

                    b.Property<string>("WorkCompletedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("WorkCompletedDate")
                        .HasColumnType("date");

                    b.Property<decimal>("WorkCompletedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("TransactionId");

                    b.HasIndex("EnteredBy")
                        .IsUnique();

                    b.HasIndex("RelatedId");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.HasIndex("WorkCompletedBy")
                        .IsUnique();

                    b.ToTable("PstsTimeTransactionss");
                });

            modelBuilder.Entity("psts.web.Data.PstsUserProfile", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("PstsUserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Psts.Web.Data.PstsClientProfile", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", "EmployeePOC")
                        .WithOne()
                        .HasForeignKey("Psts.Web.Data.PstsClientProfile", "EmployeePOCId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeePOC");
                });

            modelBuilder.Entity("Psts.Web.Data.PstsProjectDefinition", b =>
                {
                    b.HasOne("Psts.Web.Data.PstsClientProfile", "Client")
                        .WithOne()
                        .HasForeignKey("Psts.Web.Data.PstsProjectDefinition", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.AppUser", "EmployeePOC")
                        .WithOne()
                        .HasForeignKey("Psts.Web.Data.PstsProjectDefinition", "EmployeePOCId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("EmployeePOC");
                });

            modelBuilder.Entity("Psts.Web.Data.PstsTaskDefinition", b =>
                {
                    b.HasOne("Psts.Web.Data.PstsProjectDefinition", "Project")
                        .WithOne()
                        .HasForeignKey("Psts.Web.Data.PstsTaskDefinition", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("psts.web.Data.PstsBillingRateResolutionSchedule", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", "ChangedByEmployee")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsBillingRateResolutionSchedule", "ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.PstsClientProfile", "Client")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsBillingRateResolutionSchedule", "ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Psts.Web.Data.AppUser", "Employee")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsBillingRateResolutionSchedule", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Psts.Web.Data.PstsProjectDefinition", "Project")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsBillingRateResolutionSchedule", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Psts.Web.Data.PstsTaskDefinition", "Task")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsBillingRateResolutionSchedule", "TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangedByEmployee");

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("psts.web.Data.PstsTimeAdjustmentApprovalLedger", b =>
                {
                    b.HasOne("psts.web.Data.PstsTimeTransactions", "SubjectTransaction")
                        .WithOne("RelatedApproval")
                        .HasForeignKey("psts.web.Data.PstsTimeAdjustmentApprovalLedger", "ApprovedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.AppUser", "ApprovingUser")
                        .WithMany()
                        .HasForeignKey("ApprovingUserId");

                    b.Navigation("ApprovingUser");

                    b.Navigation("SubjectTransaction");
                });

            modelBuilder.Entity("psts.web.Data.PstsTimeTransactions", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", "EnteredEmployee")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsTimeTransactions", "EnteredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("psts.web.Data.PstsTimeTransactions", "RelatedTransaction")
                        .WithMany()
                        .HasForeignKey("RelatedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Psts.Web.Data.PstsTaskDefinition", "Task")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsTimeTransactions", "TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.AppUser", "WorkCompletedEmployee")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsTimeTransactions", "WorkCompletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnteredEmployee");

                    b.Navigation("RelatedTransaction");

                    b.Navigation("Task");

                    b.Navigation("WorkCompletedEmployee");
                });

            modelBuilder.Entity("psts.web.Data.PstsUserProfile", b =>
                {
                    b.HasOne("Psts.Web.Data.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("psts.web.Data.PstsUserProfile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Psts.Web.Data.AppUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("psts.web.Data.PstsTimeTransactions", b =>
                {
                    b.Navigation("RelatedApproval");
                });
#pragma warning restore 612, 618
        }
    }
}
